// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiisslyuwioisprllxvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaXNzbHl1d2lvaXNwcmxseHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTY3MzgsImV4cCI6MjA2Mjg5MjczOH0.WMg3MGv77QorfG8_UfJ4iTrp_PMm9Y6u4qXV9jejr68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);